name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a60bdf01ca047d66829442f07a983bc7112e98ef7c420706289680593b77eed"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
