name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60b53785fcd24749dc127e7762c148bf113851f210856437bc312cb749b1c991"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
