name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dac7240ba804ae1182e8577b48e86441a4720f3fbbd7f3f363e43dd88c21154"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
