name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89e3cd3337f8e1e0c7b41ce3001838d7acce0e3e06d60450e245785d8386e553"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
