name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26fac9fa1727fd891d2782eec501a9e9cb75853afb3e1c4e79b5808417f5cfe5"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
