name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "825a052e077b40c64f7ab0354b7f68def2726b813053be4d4c62ff25e71a3980"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
