name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5169009e6e913951d50ce2aeaf0758d55a01df2c38017238844b0da275038148"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
