name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d3e115ec918be5517850dcef7fcf7bd275cdbc986c5d74fe110c4a9c20a0474"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
