name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f80e0e37905f245c6e50df695ea6d64d5a37f51b8b9a8d0b8506febf50db21"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
