name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.2a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b57cc2297624345f18d6cbef76c74941d7922c93aaa676eeebe042b689ac9d5"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
