name = "Wold's Vaults"
author = "iwolfking"
version = "0.21.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f6a94a3e6541ac58b3415136a5eb1813a62d9666c69e09f69ed77b9902278ea"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
